artifact_uri: file:///C:/Users/ASUS/AndroidStudioProjects/Workflow-CI/MLProject/mlruns/0/f03c8cb53b4d4b6bb9724eb007f4ecc2/artifacts
end_time: 1762619622057
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: f03c8cb53b4d4b6bb9724eb007f4ecc2
run_name: enchanting-snipe-512
run_uuid: f03c8cb53b4d4b6bb9724eb007f4ecc2
source_name: ''
source_type: 4
source_version: ''
start_time: 1762619617067
status: 3
tags: []
user_id: runner
