digest: b073a944
name: dataset
profile: '{"num_rows": 67, "num_elements": 804}'
schema: '{"mlflow_colspec": [{"type": "double", "name": "Pregnancies", "required":
  true}, {"type": "double", "name": "Glucose", "required": true}, {"type": "double",
  "name": "BloodPressure", "required": true}, {"type": "double", "name": "SkinThickness",
  "required": true}, {"type": "double", "name": "Insulin", "required": true}, {"type":
  "double", "name": "BMI", "required": true}, {"type": "double", "name": "DiabetesPedigreeFunction",
  "required": true}, {"type": "double", "name": "Age", "required": true}, {"type":
  "double", "name": "BMI_Underweight", "required": true}, {"type": "double", "name":
  "BMI_Normal", "required": true}, {"type": "double", "name": "BMI_Overweight", "required":
  true}, {"type": "double", "name": "BMI_Obese", "required": true}]}'
source: '{"tags": {"mlflow.user": "ASUS", "mlflow.source.name": "modelling.py", "mlflow.source.type":
  "LOCAL", "mlflow.source.git.commit": "849b30f35ca78e8a371b82e1d8ca524411936b86"}}'
source_type: code
