artifact_location: file:///C:/Users/ASUS/AndroidStudioProjects/Workflow-CI/MLProject/mlruns/432753510853273160
creation_time: 1762616807747
experiment_id: '432753510853273160'
last_update_time: 1762616807747
lifecycle_stage: active
name: Diabetes_Experiment
