artifact_location: file:///C:/Users/ASUS/AndroidStudioProjects/Workflow-CI/MLProject/mlruns/0
creation_time: 1762616807710
experiment_id: '0'
last_update_time: 1762616807710
lifecycle_stage: active
name: Default
